<?php

// This file is only used to input translation strings into POEdit, it is not used in the plugin code

__('Street');
__('Zipcode');
__('Subdistrict');
__('Toilets');
__('Bathrooms');
__('Flooring');
__('Kitchen');
__('Kitchen fridge');
__('Kitchen freezer');
__('Kitchen dishwasher');
__('Kitchen furnace');
__('Kitchen oven');
__('Kitchen microwave');
__('Kitchen microwave combi');
__('Kitchen hood');
__('House type');
__('Parking');
__('Roofterrace');
__('Fridge');
__('Freezer');
__('Dishwasher');
__('Microwave combi');
__('Hood');
__('Furnace');
__('Unfurnished');
__('Furnished');
__('Bare');
__('inclusive');
__('exclusive');
__('Telephone');
__('Mobile telephone');
__('Emailaddress');
__('House address');
__('House zipcode');
__('House city');
__('House bedrooms');
__('House surface');
__('Company');
__('Name');
__('When do you want to rent');
__('Commencing date in dd-mm-yyyy');
__('Max price');
__('Other wishes');
__('View property');
__('Service costs');
__('Condition');
__('Price type');
__('Property type 2');
__('Property type 3');
__('Building type');
__('Buildyear');
__('Total rooms');
__('Surface outdoor');
__('Livinglayers');
__('Livinglayer');
__('Open porch');
__('Maintenance indoor');
__('Maintenance outdoor');
__('Rooms');
__('Seller');
__('Loft');
__('Roof type');
__('Heating');
__('Energy label');
__('Isolation');
__('Storage');
__('Basic information');
__('Building');
__('Email address');
__('Subject');
__('Field is required');
__('Netherlands');
__('country');
__('Country');
__('Gardens');
__('Balconies');
__('Storages');
__('Parkings');
__('Rented out');
__('New');
__('Spotlight');
__('Soon');
__('Top house');
__('Top property');
__('Sold');
__('Sold under reserves');
__('Rented out under reserves');
__('Lowered in price');
__('Recommended');
__('Hoofdbestemming');
__('Nevenbestemmingen');
__('Bouwgrond');
__('Bouwgrond bebouwingsmogelijkheid');
__('Bouwgrond bouwvolume procentueel');
__('Bouwgrond bouwvolume vierkante meters');
__('Bouwgrond bouwvolume bouwhoogte');
__('Bouwgrond units');
__('Company');
__('Surface');
__('Units surface');
__('Height');
__('Floor load');
__('Vrije overspanning');
__('Luchtbehandelingen');
__('Voorzieningen');
__('Prijs');
__('Btwtarief');
__('Btwbelast');
__('Office');
__('Surface');
__('Floors');
__('Units from');
__('Turnkey');
__('Luchtbehandelingen');
__('Opleveringsniveau');
__('Prijs');
__('Btwtarief');
__('Btwbelast');
__('Terrein');
__('Oppervlakte');
__('Bouwhoogte');
__('Uitbreiding procentueel');
__('Uitbreiding vierkante meters');
__('Shop');
__('Surface');
__('Floors');
__('Shopkeepers association contribution');
__('Frontal width');
__('Catering');
__('Verkoop vloeroppervlakte');
__('Branchbeperking');
__('Btwtarief');
__('Btwbelast');
__('Personeel');
__('Welstandsklasse');
__('Horeca');
__('Surface');
__('Verkoop vloer oppervlakte');
__('Verdieping');
__('Regio');
__('Soort');
__('Concentratiegebied');
__('Prijs');
__('Btwtarief');
__('Btwbelast');
__('Personeel');
__('Welstandsklasse');
__('Garagebox');
__('Praktijkruimte');
__('Showroom');
__('Location');
__('Trainstation');
__('Trainstop');
__('Tramstation');
__('Tramstop');
__('Busstation');
__('Busstop');
__('Metrostation');
__('Metrostop');
__('Highway');
__('Bank');
__('Bank aantal');
__('Ontspanning');
__('Ontspanning aantal');
__('Restaurant');
__('Restaurant aantal');
__('Winkel');
__('Winkel aantal');
__('Nietoverdekt aantal');
__('Nietoverdekt prijs');
__('Nietoverdekt btwtarief');
__('Nietoverdekt btwbelast');
__('Overdekt aantal');
__('Overdekt prijs');
__('Overdekt btwtarief');
__('Overdekt btwbelast');
__('Faciliteiten');
__('Bog bouwgrond');
__('Bog company');
__('Bog office');