<?php if ($house['lat'] != '' && get_option('nomis_property_googlemaps') == '1' || $house['lat'] != '' && get_option('nomis_property_streetview') == '1'): ?>
<div class="location">
	<div class="location-controls">
		<?php if (get_option('nomis_property_googlemaps') == '1'): ?>
		<a href="javascript:;" id="show-maps" class="location-first"><span><?php echo __('Show maps', 'nomis'); ?></span></a>
		<?php endif; if (get_option('nomis_property_streetview') == '1'): ?>
		<a href="javascript:;" id="show-streetview"<?php if (get_option('nomis_property_googlemaps') == '0') echo ' class="location-first"'; ?>><span><?php echo __('Show streetview', 'nomis'); ?></span></a>
		<?php endif; ?>
		<div class="clear"></div>
	</div>
	<div id="media-holder">
		<?php if (get_option('nomis_property_googlemaps') == '1'): ?>
		<div id="nomis-maps" class="maps" data-lat="<?php echo $house['lat']; ?>" data-lng="<?php echo $house['lng']; ?>" data-title="<?php echo $title; ?>">&nbsp;</div>
		<?php endif; if (get_option('nomis_property_streetview') == '1'): ?>
		<div id="nomis-streetview" class="streetview" data-lat="<?php echo $house['lat']; ?>" data-lng="<?php echo $house['lng']; ?>">&nbsp;</div>
		<?php endif; ?>
	</div>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
</div>
<?php endif; ?>