<div id="nomis-property-2">
	<div class="left">
		<?php include '_property_details.phtml'; ?>
		<div class="clear"></div>
		<?php include '_property_description.phtml'; ?>
		<?php include '_property_controls.phtml'; ?>
	</div>

	<div class="right">
		<?php include '_property_photos_2.phtml'; ?>
		<div class="clear"></div>
		<?php include '_property_location.phtml'; ?>
	</div>
</div>

<script type="text/javascript">
	$(window).load(showPhotoCarousel);
</script>